output-format: grouped

inherits:
  - strictness_high

ignores:
  - ^\.git/
  - ^\.tox/
  - ^\.DS_Store/
  - ^venv/
  - ^dist/
  - *\.egg-info/
  - ^img/

pylint:
  options:
    init-import: false
    max-line-length: 80
    dummy-variables-rgx: '_|kws'
    no-docstring-rgx: '_.*'
    argument-rgx: '[a-z_][a-z0-9_]{,30}$'
    attr-rgx: '[a-zA-Z_][a-zA-Z0-9_]{2,30}$'
    class-rgx: '_?[A-Z][a-zA-Z0-9]+$'
    const-rgx: '(([A-Za-z_][a-zA-Z0-9_]*)|(__.*__)|_.*)$'
    function-rgx: '_*[a-z][a-zA-Z0-9_]{,30}$'
    method-rgx: '_*[a-z][a-zA-Z0-9]{2,30}$'
    module-rgx: '[a-z][a-z0-9]+$'
    variable-rgx: '[a-z_][a-z0-9_]{,30}$'
    max-args: 8
    max-locals: 24
    max-returns: 10
    max-branchs: 30
    max-statements: 60
    max-parents: 2
    max-attributes: 20
    min-public-methods: 0
    notes:
      - FIXME
      - XXX
      - TODO

pep8:
  options:
    max-line-length: 80
